{ ... }:
{
  perSystem =
    { pkgs, config, ... }:
    let
      inherit (pkgs) lib;
      klfc = lib.getExe config.packages.klfc;

      layouts = ./layouts;

      # Every layout is composed from the same pieces: a metadata file, a base,
      # then the shared mod3 and CapsLock overlays. Overlays whose shiftlevel
      # name matches the base override that level; a new name would append one.
      compose = parts: lib.concatMapStringsSep " " (p: "${layouts}/${p}") parts;

      us = compose [
        "meta/us.json"
        "base/us.json"
        "mod3.json"
        "capslock.json"
      ];
      # BR on an ANSI board is the US base plus Portuguese dead keys, matching
      # the Ukelele layout it replaces - not ABNT2, whose keys sit elsewhere.
      br = compose [
        "meta/br.json"
        "base/us.json"
        "pt-deadkeys.json"
        "mod3.json"
        "capslock.json"
      ];
      abnt2 = compose [
        "meta/abnt2.json"
        "base/abnt2.json"
        "mod3.json"
        "capslock.json"
      ];

      # TMK is the one output we never use, and it warns on every dead key.
      generate = pkgs.runCommand "keyboard-generated" { } ''
        mkdir -p "$out"
        for spec in "us:${us}" "br:${br}" "abnt2:${abnt2}"; do
          name="''${spec%%:*}"
          ${klfc} --from-json ''${spec#*:} \
            --xkb "$out/$name/xkb" \
            --keylayout "$out/$name/keylayout" \
            --klc "$out/$name/klc" \
            --pkl "$out/$name/pkl"
        done
      '';

      bundleConfig = pkgs.writeText "keyboard-bundle.json" (
        builtins.toJSON {
          identifier = "org.sil.ukelele.keyboardlayout.guilh";
          bundleName = "Guilh";
          version = "1.0";
          # Ids match the previous Ukelele bundle so macOS keeps treating these
          # as the same input sources; ABNT2 is new and gets a free one.
          layouts = [
            {
              name = "US - Guilh";
              src = "${generate}/us/keylayout/US-Guilh.keylayout";
              id = -9970;
              language = "en";
              ansi = true;
            }
            {
              name = "BR - Guilh";
              src = "${generate}/br/keylayout/BR-Guilh.keylayout";
              id = -14179;
              language = "pt-BR";
              ansi = true;
            }
            {
              name = "ABNT2 - Guilh";
              src = "${generate}/abnt2/keylayout/ABNT2-Guilh.keylayout";
              id = -14180;
              language = "pt-BR";
              ansi = false;
            }
          ];
        }
      );

      bundle = pkgs.runCommand "Guilh.bundle" { } ''
        ${lib.getExe pkgs.python3} ${./darwin/mkbundle.py} ${bundleConfig} "$out"
      '';

      # XKB: wrap KLFC's standalone symbols file as a `custom` variant so the
      # session line already configured in XFCE (br,us : custom,custom) keeps
      # working. The marker is what install.sh matches on to replace an older
      # block, so it must not be renamed.
      mkSection =
        name: src:
        pkgs.runCommand "xkb-${name}-custom" { } ''
          {
            printf '// >>> xkbd-custom (managed by `nix run .#keyboard-linux`) — do not edit >>>\n'
            printf 'partial alphanumeric_keys\n'
            sed -e '/^default$/d' \
                -e 's/^xkb_symbols "basic"/xkb_symbols "custom"/' \
                -e '/^\/\/ Generated by KLFC/d' \
                -e '/^\/\/ https:\/\/github.com\/39aldo39\/klfc/d' \
                ${src}
            printf '// <<< xkbd-custom <<<\n'
          } > "$out"
        '';

      brSection = mkSection "br" "${generate}/abnt2/xkb/symbols/ABNT2-Guilh";
      usSection = mkSection "us" "${generate}/us/xkb/symbols/US-Guilh";
    in
    {
      packages.keyboard-generated = generate;

      packages.keyboard-linux = pkgs.writeShellApplication {
        name = "keyboard-linux";
        runtimeInputs = with pkgs; [ coreutils ];
        runtimeEnv = {
          BR_SECTION = brSection;
          US_SECTION = usSection;
        };
        text = builtins.readFile ./linux/install.sh;
      };

      packages.xkbd-custom = config.packages.keyboard-linux;

      packages.keyboard-darwin = pkgs.writeShellApplication {
        name = "keyboard-darwin";
        runtimeInputs = with pkgs; [
          coreutils
          diffutils
          findutils
        ];
        runtimeEnv.BUNDLE = bundle;
        text = builtins.readFile ./darwin/install.sh;
      };

      packages.keyboard-darwin-bundle = bundle;

      # PKL runs the layout on Windows with no MSKLC and no admin rights, and
      # unlike .klc it can carry CapsLock->Escape. The .klc files are kept for
      # the MSKLC route, re-encoded to the UTF-16LE that MSKLC insists on.
      packages.keyboard-windows = pkgs.runCommand "keyboard-windows" { } ''
        mkdir -p "$out"
        for name in us abnt2; do
          cp -r "${generate}/$name/pkl" "$out/$name"
          chmod -R u+w "$out/$name"
          mkdir -p "$out/$name/klc"
          for f in "${generate}/$name"/klc/*.klc; do
            ${lib.getExe pkgs.python3} ${./windows/to-msklc.py} \
              "$f" "$out/$name/klc/$(basename "$f")"
          done
        done
      '';
    };
}
